# Generated by Django 2.0.5 on 2018-05-30 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('underdog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spread', models.FloatField()),
                ('week', models.IntegerField()),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='underdog.NFLTeam')),
            ],
        ),
    ]
