# Generated by Django 2.0.5 on 2018-05-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('underdog', '0003_auto_20180530_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchupModel',
            new_name='Matchup',
        ),
    ]
