# Generated by Django 2.0.5 on 2018-06-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('underdog', '0004_auto_20180531_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='underdog.Matchup')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='underdog.Person')),
            ],
        ),
    ]
