# Generated by Django 2.0.5 on 2018-06-03 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('underdog', '0005_person_pick'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_score', models.IntegerField()),
                ('underdog_score', models.IntegerField()),
                ('points_for_pick', models.FloatField()),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='underdog.Matchup')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='underdog.NFLTeam')),
            ],
        ),
    ]
