# Generated by Django 2.0.5 on 2018-06-04 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('underdog', '0006_gameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pick',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
