# Generated by Django 2.0.5 on 2018-06-04 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('underdog', '0007_auto_20180604_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='game_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 16, 52, 1, 397132, tzinfo=utc)),
        ),
    ]
