# Generated by Django 2.0.5 on 2018-06-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underdog', '0008_matchup_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='game_time',
            field=models.DateTimeField(),
        ),
    ]
