# Generated by Django 2.0.5 on 2018-06-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underdog', '0009_auto_20180604_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='home_team',
            field=models.CharField(choices=[('FAV_TEAM', 'Favorite'), ('UNDER_TEAM', 'Underdog')], default='FAV_TEAM', max_length=15),
        ),
    ]
