# Generated by Django 2.0.5 on 2018-06-07 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('underdog', '0011_auto_20180605_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
